#! /bin/sh
#
# Gideon's bspwmrc file.
# Please note, this is by no 
# means anything special.
# ^_^
#
#----------------------------
# Some config
#----------------------------

bspc config border_width 1
bspc config window_gap 22
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer false

#----------------------------
# Border Colors
#----------------------------

bspc config normal_border_color "#3f3e3b"
bspc config active_border_color "#dd7162"
bspc config focused_border_color "#dd7162"
bspc config presel_border_color "#8c8c8c"

#----------------------------
# Monitor names
#----------------------------

bspc monitor -d main internet code music manga anime series games misc edit

#----------------------------
# Rules
#----------------------------

bspc rule -a gimp-2.8 desktop=^10 follow=on floating=on
bspc rule -a Steam desktop=^8
bspc rule -a sun-awt-X11-XFramePeer desktop=^3

#----------------------------
# Set wallpaper
#----------------------------

feh --bg-scale ~/.config/bspwm/wallpaper/current.jpg

#----------------------------
# Launch stuff
#----------------------------

#----------------------------
# first, lets setup ncmpcpp
#----------------------------

bspc rule -a URxvt desktop=^4 split_ratio=0.50 focus=off &
sleep 0.1
urxvt -e ncmpcpp -s playlist &
sleep 0.1
urxvt -e ncmpcpp -s browser &
sleep 0.1
bspc rule -a URxvt desktop=^4 split_ratio=0.80 focus=off &
sleep 0.1
urxvt -e ncmpcpp -s visualizer &
sleep 0.2
bspc rule -r URxvt desktop=^4 split_ratio=0.50 focus=off &
bspc rule -r URxvt desktop=^4 split_ratio=0.80 focus=off &

compton &
guake &
panel &
